### ISSUE TITLE
Can’t use app

### ISSUE THREAD

**Issue by SLStewart54** [eugene-khyst/artistassistapp#14]
For the past few days, I have not been able to use the app. The app opens with the message: “InvalidStateError: An error occurred reading the Blob argument to createImageBitmap”. Every time I try to go to a different page I get the same error message.

**Comment by SLStewart54** [comment]
Hello? I would like to continue to use the app, but I checked today and the error message is still there. I’m on an iPad Air, 4th generation, OS17.5.1. Please respond.

**Comment by eugene-khyst** [comment]
Hi! I will try to fix this bug in the next release. But it will take a few days.
Meanwhile, try to open the app in another browser. For example, install Google Chrome, if you usually use Safari.

**Comment by eugene-khyst** [comment]
Hi @SLStewart54 
I will try to fix this bug in the next release. But it will take a few days.
Meanwhile, try to open the app in another browser. For example, install Google Chrome, if you usually use Safari.

**Comment by eugene-khyst** [comment]
@SLStewart54, the bug is fixed, please check out the app.
