### ISSUE TITLE
Not uploading images

### ISSUE THREAD

**Issue by CpnEyeball** [eugene-khyst/artistassistapp#2]
The site has entirely stopped uploading new images. I’ve been thrilled exploring your brilliant web app for several days. Now that it won’t upload new photos the whole thing is pretty useless :(

**Comment by CpnEyeball** [comment]
Is anyone not having this problem?

**Comment by eugene-khyst** [comment]
Hi @CpnEyeball 

What web browser and what version are you using?
You can check it by clicking the Help `(?)` link in the top bar and copying the bottom text line.

![image](https://github.com/eugene-khyst/artistassistapp/assets/1311126/170bcd5e-85b0-4c37-a429-9a56673125a8)

**Comment by CpnEyeball** [comment]
﻿﻿Thanks for getting back to me so quickly on this. I’m using mobile devices with Apple iOS 17.1.2. The browsers I have are Chrome and Safari. Since these are mobile devices I don’t have any info on browser versions other than which iOS I’m using. On Dec 22, 2023, at 10:47 PM, Eugene Khyst ***@***.***> wrote:﻿
Hi @CpnEyeball
What web browser and what version are you using?
You can check it by clicking the Help (?) link in the top bar and copying the bottom text line.
image.png (view on web)

**Comment by CpnEyeball** [comment]
Hey again, Eugene. I just installed a new mobile browser app — Firefox — and the problem with uploading new images persists. It’s odd bc everything was working beautifully until a few days ago 😞 On Dec 23, 2023, at 9:32 AM, Adlai Burman ***@***.***> wrote:﻿﻿﻿Thanks for getting back to me so quickly on this. I’m using mobile devices with Apple iOS 17.1.2. The browsers I have are Chrome and Safari. Since these are mobile devices I don’t have any info on browser versions other than which iOS I’m using. <image0.png>On Dec 22, 2023, at 10:47 PM, Eugene Khyst ***@***.***> wrote:﻿
Hi @CpnEyeball
What web browser and what version are you using?
You can check it by clicking the Help (?) link in the top bar and copying the bottom text line.
image.png (view on web)

**Comment by eugene-khyst** [comment]
@CpnEyeball, try now, the problem should be solved.

**Comment by eugene-khyst** [comment]
The root cause is https://github.com/ant-design/ant-design/issues/46598

**Comment by CpnEyeball** [comment]
Indeed it is!Thanks Eugene. On Dec 23, 2023, at 1:28 PM, Eugene Khyst ***@***.***> wrote:﻿
@CpnEyeball, try now, the problem should be solved.

**Comment by CpnEyeball** [comment]
Thank you 🙏 On Dec 23, 2023, at 1:53 PM, Eugene Khyst ***@***.***> wrote:﻿
The root cause is ant-design/ant-design#46598

**Comment by yoyo837** [comment]
ref: https://github.com/react-component/input/pull/58
