### ISSUE TITLE
Additional brand watercolors

### ISSUE THREAD

**Issue by Jeannette-too** [eugene-khyst/artistassistapp#22]
Will there come a time when brand colors without numbers, i.e. Daniel Smith Transparent Oxide Brown and Quin. Rose will be available for selection? Also, could you please add Holbein Artist Watercolor Marine Blue #302?
Thanks!
Jeannette

**Comment by eugene-khyst** [comment]
Hi @Jeannette-too, 
I will try to add these colors tomorrow and let you know.

**Comment by Jeannette-too** [comment]
Thank you!Jeannette Childers
    On Saturday, August 10, 2024 at 01:07:03 PM MST, Eugene Khyst ***@***.***> wrote:  
 
 


Hi @Jeannette-too,
I will try to add these colors tomorrow and let you know.

**Comment by eugene-khyst** [comment]
Hi @Jeannette-too,

I've recently added Holbein Artist Watercolor Marine Blue.
But Daniel Smith Transparent Brown Oxide and Quinacridone Rose were already available.
See the screenshot.
![Screenshot from 2024-08-11 15-47-36](https://github.com/user-attachments/assets/e96244f1-3d19-4921-8899-7cb68c48cc52)

**Comment by Jeannette-too** [comment]
Thank you! I truly did look and don't know how I missed them! Is there a way to do a search within the brand name boundaries for a color?
I want to acknowledge all the work that has been put into this program. I'm excited to see how I can utilize it in my art.
Jeannette Childers 
    On Sunday, August 11, 2024 at 05:50:34 AM MST, Eugene Khyst ***@***.***> wrote:  
 
 


Hi @Jeannette-too,

I've recently added Holbein Artist Watercolor Marine Blue.
But Daniel Smith Transparent Brown Oxide and Quinacridone Rose were already available.
See the screenshot.
Screenshot.from.2024-08-11.15-47-36.png (view on web)

**Comment by eugene-khyst** [comment]
@Jeannette-too, I've improved the color filtering in the ArtistAssistApp after your request. Now, you will find Transparent Oxide Brown even by typing only "transp brow ox". The same is for Quinacridone Rose, you will find it by typing "quin ro".
By the way, if you find ArtistAssistApp useful, please tell your artist friends about it 🙏
![Screenshot from 2024-08-11 18-15-25](https://github.com/user-attachments/assets/a45099a9-4700-4f56-88e0-fc13efbc6df7)
![Screenshot from 2024-08-11 18-16-24](https://github.com/user-attachments/assets/0526e3b1-2c1a-4d85-a205-db8c9fa75bd8)

**Comment by Jeannette-too** [comment]
Awesome!I have already posted links to the app in all the art groups I belong to on FB. I don't have many art friends who are computer users like I am (even my artistic daughter is more organic!), but I'll certainly spread the word! Jeannette     On Sunday, August 11, 2024 at 08:17:50 AM MST, Eugene Khyst ***@***.***> wrote:  
 
 


@Jeannette-too, I've improved the color filtering in the ArtistAssistApp after your request. Now, you will find Transparent Oxide Brown even by typing only "transp brow ox". The same is for Quinacridone Rose, you will find it by typing "quin ro".
By the way, if you find ArtistAssistApp useful, please tell your artist friends about it 🙏
Screenshot.from.2024-08-11.18-15-25.png (view on web)
Screenshot.from.2024-08-11.18-16-24.png (view on web)
