### ISSUE TITLE
Adding a Brand

### ISSUE THREAD

**Issue by Ronsmail** [eugene-khyst/artistassistapp#25]
How can I get the brand of paint that I use added? It would be a great feature if we were able to scan or take a photo of a color, like we do when depositing a check with our phone, and it’s added. Sounds complicated but that would be a valuable feature. You might be able to add a color on the fly. Thank you, wonderful Application!

**Comment by eugene-khyst** [comment]
Hi @Ronsmail 
Photo of your color swatch made with your phone will have absolutely different colors compared to real life. At least due to problems with white balance. Try taking a photo of a white paper with your phone on the streen with daylight and in a room with lamp light. You will see how different the same white psper looks in different light. The same is true for cloudy and sunny weather.
At the moment J have no ideas how to implement such feature.

**Comment by Ronsmail** [comment]
Understood.
I did search a bit more and see where you submit other brands. I will visit Vasari Artists Paints, their factory is close to me, and show her the Ap and show her the process of submitting.
They are a professional grade oil paint.
Thanks for answering my question

Ron


On Sep 10, 2024, at 6:22 AM, Eugene Khyst ***@***.***> wrote:

﻿

Hi @Ronsmail<https://github.com/Ronsmail>
Photo of your color swatch made with your phone will have absolutely different colors compared to real life. At least due to problems with white balance. Try taking a photo of a white paper with your phone on the streen with daylight and in a room with lamp light. You will see how different the same white psper looks in different light. The same is true for cloudy and sunny weather.
At the moment J have no ideas how to implement such feature.

**Comment by eugene-khyst** [comment]
@Ronsmail there are some more details about the color information I need to add a new brand to the app here: https://github.com/eugene-khyst/artistassistapp/discussions/23#discussion-7053082

- The most precise color information can be achieved by using Spectrophotometer (here is a video explaining what it is: https://www.youtube.com/watch?v=kXsCJwBIX14).
- Some manufacturers provide CIE L\*a\*b\* color information. This is also quite a precise option.
- Alternatively high quality color chart or color swatches with right white balance (ideally CIE illuminant D60) can be used to extract sRGS color information. sRGB color space gamut is limited. But most displays anyway operate in sRGS color space so, it's OK.

**Comment by eugene-khyst** [comment]
Hi @Ronsmail 

A few more times ArtistAssistApp users have asked about creating their own color brands from swatch photos. Thus, I implemented this feature in a new “Custom Brand” tab.

To add your own color brand to ArtistAssistApp:

1. Swatch all your colors
2. Take a high quality photo
3. Adjust white balance using the "White balance" tab of ArtistAssistApp
4. On the new "Custom brand" tab select the image with swatches, use color picker to extract color info, give names to the brand and colors, and press "Save".

![Adding custom color brand to ArtistAssistApp](https://github.com/user-attachments/assets/66473a30-4289-4467-9a07-b3b6cecd2e6a)

![Choosing colors of a custom brand](https://github.com/user-attachments/assets/3a55de82-5936-4fc0-93d3-ba0f2840c805)
