### ISSUE TITLE
Grid feature combined with outline feature

### ISSUE THREAD

**Issue by Jeannette-too** [eugene-khyst/artistassistapp#28]
I would be wonderful if I could put a grid over an outline. It would get rid of the "color clutter" and make the drawing easier to accomplish. Could that be done?
Thank you for continuing to "push" through all the headaches/heartaches that go into starting a new venture. I think this is a wonderful adjunct to my art journey and tell everyone about it every chance I get.
Jeannette

**Comment by eugene-khyst** [comment]
Hi Jeannette,
This is already possible but requires a few steps.

1. Import the original photo
2. Click the "Save" button on the Outline tab
3. Import saved ArtistAssistApp-Outline.png file
4. Open the Grid tab

![Outline](https://github.com/user-attachments/assets/ba38a689-ac2a-447e-8bce-f4767150f47c)

![Outline + Grid](https://github.com/user-attachments/assets/d434014e-05cd-484b-98e6-5d188cd64d26)

I will create a video tutorial about it.

**Comment by Jeannette-too** [comment]
Oh, never thought of doing that! Thank you!Jeannette
    On Sunday, November 17, 2024 at 10:45:08 AM MST, Eugene Khyst ***@***.***> wrote:  
 
 


Hi @Jeannette-too
This is already possible but requires a few steps.
   
   - Import the original photo
   - Click the "Save" button on the Outline tab
   - Import saved ArtistAssistApp-Outline.png file
   - Open the Grid tab

Screenshot_20241117_193918_Chrome.jpg (view on web)

Screenshot_20241117_193902_Chrome.jpg (view on web)

I will create a video tutorial about it.

**Comment by Jeannette-too** [comment]
Just tried it! Easy and awesome!!!J
    On Sunday, November 17, 2024 at 10:44:19 AM MST, Eugene Khyst ***@***.***> wrote:  
 
 


Hi Jeannette,
This is already possible but requires a few steps.
   
   - Import the original photo
   - Click the "Save" button on the Outline tab
   - Import saved ArtistAssistApp-Outline.png file
   - Open the Grid tab

Screenshot_20241117_193918_Chrome.jpg (view on web)

Screenshot_20241117_193902_Chrome.jpg (view on web)

I will create a video tutorial about it.
