### ISSUE TITLE
saved color set gone?

### ISSUE THREAD

**Issue by lafrizz** [eugene-khyst/artistassistapp#30]
joined patreon, used magic link when all else failed, read community Q&A, it says welcome thanks for your support on patreon, and there is no existing color set. which I KNOW I entered AFTER joining on Patreon

**Comment by lafrizz** [comment]
it appears the color set didn't save (although I did indeed save it)  AND when i try to enter a new one, i enter the name and when i hit return, the name disappears.  I am using Firefox on windows 11.

**Comment by eugene-khyst** [comment]
Hi @lafrizz,
This article, which includes a video, provides instructions on how to create a color set. https://artistassistapp.com/en/tutorials/color-set/
This tutorial provides instructions on how to save the color set into a shareable link. https://artistassistapp.com/en/tutorials/share-color-set/
Use this link to restore your color set on any device.
ArtistAssistApp does not store your color sets on its servers, as it does not have any servers. The web browser stores all data, including color sets. This means that if you manually clear your website data, use a cleaner app, or open ArtistAssistApp on a different device, you won't have any color sets or photos.
I apologize for the loss of your color set, but the clearing of the web browser's data is the only explanation.
To avoid such a situation in the future, consider saving links to your color sets somewhere in notes (e.g., Google Keep).

When you enter any field and hit "Enter," it is the same as pressing the "Save & Proceed" button. Press "Tab" to move to the next field.

**Comment by lafrizz** [comment]
huge thanks for this.... and if the info is offered in tutorials, when I go there, I see how to paint xyz, not basic operation instructions.  Perhaps pin them to the top?
